--{program="bMobFarm",version="1.01",date="2015-01-05",basicFunc="xxx",basicFuncDate="xxx",addFunc="xxx"",addFuncDate="xxx"}
---------------------------------------
-- bMobFarm            by Kaikaku
-- 2015-01-05, v1.01   renamed to bMobFarm,
--                     turtle waits for enter
-- 2013-25-10, v1.00   initial 
---------------------------------------


---------------------------------------
---- PARAMETERS ----------------------- 
---------------------------------------
local cVersion  ="v1.01"


---------------------------------------
-- basic functions for turtle control -
---------------------------------------
local function gf()  while not turtle.forward()   do end end
local function gb()  while not turtle.back()      do end end
local function gu()  while not turtle.up()        do end end
local function gd()  while not turtle.down()      do end end
local function gl()  while not turtle.turnLeft()  do end end
local function gr()  while not turtle.turnRight() do end end
local function df()  turtle.dig()       end
local function du()  turtle.digUp()     end
local function dd()  turtle.digDown()   end
local function pf()  turtle.place()     end
local function pu()  turtle.placeUp()   end
local function pd()  turtle.placeDown() end
local function sf()  turtle.suck()      end
local function su()  turtle.suckUp()    end
local function sd()  turtle.suckDown()  end
local function Df()  turtle.drop()      end
local function Du()  turtle.dropUp()    end
local function Dd()  turtle.dropDown()  end
local function ss(s) turtle.select(s)   end

local function askForInputText(textt)
  local at=""
  -- check prompting texts
  if textt==nil then textt="Enter text:" end
  
  -- ask for input
  write(textt)
  at=read() 
  return at
end

---------------------------------------
-- additional functions               -
---------------------------------------
local function water()
  for i=1,8 do gf() end
  gf() gl() ss(12) pf() gr() gr() 
  ss(13) pf() gl() gb() os.sleep(0.8) 
  pf() os.sleep(0.8) ss(12) pf()
  gl() gl() gf() gf() gf() gf() gf() sf() sf()
  gf() gf() gf()
end

local function getTorches()
  ss(12) df() pf() os.sleep(0.3) pf() gf() gl()
  for i=1,11 do gf() end
end

---------------------------------------
-- builder program --------------------
---------------------------------------
term.clear() term.setCursorPos(1,1)
repeat
 print("+-------------------------------------+")
 print("| bMobFarm ",cVersion,", by Kaikaku (1/4)    |")
 print("+-------------------------------------+")
 print("| Turtle set-up:                      |")
 print("|   Put in slot no. listed materials: |")
 print("|    1-11: cobble       (each 64)     |")
 print("|   12+13: water bucket (each 1)      |")
 print("|      16: torches      (26)          |")
 print("|   And place a chest with further    |")
 print("|   10 stacks of cobble behind turtle |")
 print("|                                     |")
 print("+-------------------------------------+")
until askForInputText("Press enter when ready:")==""

term.clear() term.setCursorPos(1,1)
repeat
 print("+-------------------------------------+")
 print("| bMobFarm ",cVersion,", by Kaikaku (2/4)    |")
 print("+-------------------------------------+")
 print("| Option A: Explosion protection      |")
 print("|   Replace cobble in slot 1 with     |")
 print("|   obsidian (60)                     |")
 print("|                                     |")
 print("| Option B: Ladder to roof            |")
 print("|   Put in slot 14 cobble  (44)       |")
 print("|   and in slot 15 ladders (28)       |")
 print("|                                     |")
 print("+-------------------------------------+")
until askForInputText("Press enter when ready:")==""

term.clear() term.setCursorPos(1,1)
repeat
 print("+-------------------------------------+")
 print("| bMobFarm ",cVersion,", by Kaikaku (3/4)    |")
 print("+-------------------------------------+")
 print("| Option C: Creeper face on roof      |")
 print("|   Replace cobble in slot 10 (mouth) |")
 print("|   and slot 11 (eyes) with other     |")
 print("|   opaque block (e.g. black wool)    |")
 print("|   10: 54 blocks                     |")
 print("|   11: 32 blocks                     |")
 print("|                                     |")
 print("|                                     |")
 print("+-------------------------------------+")
until askForInputText("Press enter when ready:")==""

term.clear() term.setCursorPos(1,1)
repeat
 print("+-------------------------------------+")
 print("| bMobFarm ",cVersion,", by Kaikaku (4/4)    |")
 print("+-------------------------------------+")
 print("| Hint:                               |")
 print("| If you don't have enough of one     |")
 print("|   block type, you may use also any  |")
 print("|   other full stack of opaque blocks |")
 print("|   as replacement (turtle + chest).  |")
 print("|   Maybe this way you find out       |")
 print("|   further decoration options ;)     |")
 print("|                                     |")
 print("+-------------------------------------+")
until askForInputText("Press enter when ready:")==""

-- variables 
local noLadder=turtle.getItemCount(14)+turtle.getItemCount(15)

 term.clear() term.setCursorPos(1,1)
 print("Let's build something nice: Drop shaft")
 print("  working on layer 1 ...") gl()
 gl() gb() gb() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() gr()
 gb() gr() gb() gb() ss(2) pf() gb()
 gb() gb() gl() gb() ss(2) pf() gl()
 gb() gb() gb() gb() gb() ss(2) pf()
 gb() ss(15) pf() gr() gb() gr() gb()
 gb() gb() ss(2) pf() gb() gb() gb()
 gl() gb() ss(2) pf() gl() gb() gb()
 gb() gb() gb() gr() gr() gb() gb()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() gr() gb() gb() gb()
 gb() gl() gu()
 print("  working on layer 2 ...") gl()
 gl() gb() gb() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() gr()
 gb() gr() gb() gb() ss(2) pf() gb()
 gb() gb() gl() gb() ss(2) pf() gl()
 gb() ss(2) pf() gb() gb() gb() gb()
 ss(2) pf() gb() ss(15) pf() gr() gb()
 gr() gb() gb() gb() ss(2) pf() gb()
 gb() gb() gl() gb() ss(2) pf() gl()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() gr() gb()
 gb() gb() gb() gl() gu()
 print("  working on layer 3 ...") gl()
 gl() gb() gb() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() gr()
 gb() gr() gb() gb() ss(1) pf() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() ss(1) pf() gb() gb() gb() gb()
 ss(1) pf() gb() ss(15) pf() gr() gb()
 gr() gb() gb() gb() ss(1) pf() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() gr() gb()
 gb() gb() gb() gl() gu()
 print("  working on layer 4 ...") gl()
 gl() gb() gb() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() gr()
 gb() gr() gb() gb() ss(1) pf() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() ss(1) pf() gb() gb() gb() gb()
 ss(1) pf() gb() ss(15) pf() gr() gb()
 gr() gb() gb() gb() ss(1) pf() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() gr() gb()
 gb() gb() gb() gl() gu()
 print("  working on layer 5 ...") gl()
 gl() gb() gb() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() gr()
 gb() gr() gb() gb() ss(1) pf() gb()
 ss(16) pf() gb() gb() gl() gb() ss(1)
 pf() gl() gb() ss(1) pf() gb() ss(16)
 pf() gb() gb() gb() ss(1) pf() gb()
 ss(15) pf() gr() gb() gr() gb() gb()
 gb() ss(1) pf() gb() ss(16) pf() gb()
 gb() gl() gb() ss(1) pf() gl() gb()
 gb() gb() gb() gb() gr() gr() gb()
 gb() gb() ss(1) pf() gb() ss(1) pf()
 gb() ss(1) pf() gb() gr() gb() gb()
 gb() gb() gl() gu()
 print("  working on layer 6 ...") gl()
 gl() gb() gb() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() gr()
 gb() gr() gb() gb() ss(1) pf() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() ss(1) pf() gb() gb() gb() gb()
 ss(1) pf() gb() ss(15) pf() gr() gb()
 gr() gb() gb() gb() ss(1) pf() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() gr() gb()
 gb() gb() gb() gl() gu()
 print("  working on layer 7 ...") gl()
 gl() gb() gb() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() gr()
 gb() gr() gb() gb() ss(1) pf() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() ss(1) pf() gb() gb() gb() gb()
 ss(1) pf() gb() ss(15) pf() gr() gb()
 gr() gb() gb() gb() ss(1) pf() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() gr() gb()
 gb() gb() gb() gl() gu()
 print("  working on layer 8 ...") gl()
 gl() gb() gb() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() gr()
 gb() gr() gb() gb() ss(2) pf() gb()
 gb() gb() gl() gb() ss(2) pf() gl()
 gb() ss(2) pf() gb() gb() gb() gb()
 ss(2) pf() gb() ss(15) pf() gr() gb()
 gr() gb() gb() gb() ss(2) pf() gb()
 gb() gb() gl() gb() ss(2) pf() gl()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() gr() gb()
 gb() gb() gb() gl() gu()
 print("  working on layer 9 ...") gl()
 gl() gb() gb() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() gr()
 gb() gr() gb() gb() ss(2) pf() gb()
 gb() gb() gl() gb() ss(2) pf() gl()
 gb() ss(2) pf() gb() gb() gb() gb()
 ss(2) pf() gb() ss(15) pf() gr() gb()
 gr() gb() gb() gb() ss(2) pf() gb()
 gb() gb() gl() gb() ss(2) pf() gl()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() gr() gb()
 gb() gb() gb() gl() gu()
 print("  working on layer 10 ...")
 gl() gl() gb() gb() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 gr() gb() gr() gb() gb() ss(2) pf()
 gb() gb() gb() gl() gb() ss(2) pf()
 gl() gb() ss(2) pf() gb() gb() gb()
 gb() ss(2) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(2) pf()
 gb() gb() gb() gl() gb() ss(2) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 11 ...")
 gl() gl() gb() gb() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 gr() gb() gr() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(2) pf()
 gl() gb() ss(3) pf() gb() gb() gb()
 gb() ss(3) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 12 ...")
 gl() gl() gb() gb() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 gr() gb() gr() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() ss(3) pf() gb() gb() gb()
 gb() ss(3) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 13 ...")
 gl() gl() gb() gb() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 gr() gb() gr() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() ss(3) pf() gb() gb() gb()
 gb() ss(3) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 14 ...")
 gl() gl() gb() gb() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 gr() gb() gr() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() ss(3) pf() gb() gb() gb()
 gb() ss(3) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 15 ...")
 gl() gl() gb() gb() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 gr() gb() gr() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() ss(3) pf() gb() gb() gb()
 gb() ss(3) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 16 ...")
 gl() gl() gb() gb() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 gr() gb() gr() gb() gb() ss(3) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() ss(3) pf() gb() gb() gb()
 gb() ss(3) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(4) pf()
 gb() gb() gb() gl() gb() ss(3) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 17 ...")
 gl() gl() gb() gb() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 gr() gb() gr() gb() gb() ss(4) pf()
 gb() gb() gb() gl() gb() ss(4) pf()
 gl() gb() ss(4) pf() gb() gb() gb()
 gb() ss(4) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(4) pf()
 gb() gb() gb() gl() gb() ss(4) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 18 ...")
 gl() gl() gb() gb() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 gr() gb() gr() gb() gb() ss(4) pf()
 gb() gb() gb() gl() gb() ss(4) pf()
 gl() gb() ss(4) pf() gb() gb() gb()
 gb() ss(4) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(4) pf()
 gb() gb() gb() gl() gb() ss(4) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 19 ...")
 gl() gl() gb() gb() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 gr() gb() gr() gb() gb() ss(4) pf()
 gb() gb() gb() gl() gb() ss(4) pf()
 gl() gb() ss(4) pf() gb() gb() gb()
 gb() ss(4) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(4) pf()
 gb() gb() gb() gl() gb() ss(4) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 20 ...")
 gl() gl() gb() gb() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 gr() gb() gr() gb() gb() ss(4) pf()
 gb() gb() gb() gl() gb() ss(4) pf()
 gl() gb() ss(4) pf() gb() gb() gb()
 gb() ss(4) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(4) pf()
 gb() gb() gb() gl() gb() ss(4) pf()
 gl() gb() gb() gb() gb() gb() gr()
 gr() gb() gb() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() gr()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 21 ...")
 gl() gl() gb() gb() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gr() gb() gr() gb() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() gb() gb() gb() gb()
 gb() gb() ss(4) pf() gb() gb() gb()
 gl() gb() ss(4) pf() gl() gb() ss(4)
 pf() gb() gb() gb() gb() ss(4) pf()
 gb() ss(15) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gr() gb() gr() gb() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() gb() gb() gb() gb()
 gb() gb() ss(4) pf() gb() gb() gb()
 gl() gb() ss(4) pf() gl() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 gr() gb() gb() gb() gb() gl() gu()
 print("  working on layer 22 ...")
 gl() gl() gb() gb() gb() ss(2) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 gb() gb() gb() gb() gb() gb() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gr() gb() gr() gb() ss(14)
 pf() gb() gb() gb() gb() ss(14) pf()
 gb() ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() ss(5) pf() gb() gb()
 gb() gl() gb() ss(5) pf() gl() gb()
 ss(5) pf() gb() gb() gb() gb() ss(5)
 pf() gb() gb() gb() gb() gb() gb()
 gb() ss(16) pf() gb() ss(14) pf() gb()
 ss(15) pf() gr() gb() ss(14) pf() gr()
 gb() ss(14) pf() gb() gb() gb() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(5) pf() gb() gb() gb() gl() gb()
 ss(5) pf() gl() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gr() gr() gb() gb()
 ss(14) pf() gb() ss(14) pf() gb()
 ss(14) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() ss(5) pf() gb() ss(5)
 pf() gb() ss(5) pf() gb() gr() gb()
 gb() gb() gb() gl() gu()
 print("  working on layer 23 ...")
 gl() gl() gb() gb() gb() ss(5) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 gr() gb() gr() gb() gb() ss(5) pf()
 gb() gb() gb() gl() gb() ss(5) pf()
 gl() gb() ss(5) pf() gb() gb() gb()
 gb() ss(5) pf() gb() gb() gb() gb()
 gb() gb() gb() gb() ss(14) pf() gb()
 ss(15) pf() gr() gb() gr() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() ss(5) pf() gb() gb() gb()
 gl() gb() ss(5) pf() gl() gb() gb()
 gb() gb() gb() gr() gr() gb() gb()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(5) pf() gb() gr() gb() gb() gb()
 gb() gl() gd() gd() gd() gd() gd()
 gd() gd() gd() gd() gd() gd() gd()
 gd() gd() gd() gd() gd() gd() gd()
 gd() gd() gd()
 print("  Done: Drop shaft")
 
-- restock & go up ---------------
gl() gl() ss(9) Df() ss(5) Df() 
ss(1) Df()  
for i=1,8 do sf() end
ss(9) Df()
if noLadder==0 then ss(14) Df() ss(15) Df() end
gr() gr()
for i=1,23 do gu() end
for i=1,8 do gb() end gr()
for i=1,8 do gb() end gl()

 print("Next part: lower half spawn area")
 print("  working on layer 1 ...") gl()
 gl() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() ss(14)
 pf() gb() gr() gb() gr() gb() gb()
 ss(7) pf() gb() ss(7) pf() gb() ss(7)
 pf() gl() gb() gl() gb() gb() ss(7)
 pf() gb() ss(7) pf() gb() ss(7) pf()
 gr() gb() gr() gb() gb() ss(7) pf()
 gb() ss(7) pf() gb() ss(7) pf() gl()
 gb() gl() gb() gb() ss(7) pf() gb()
 ss(7) pf() gb() ss(7) pf() gr() gb()
 gr() gb() gb() ss(7) pf() gb() ss(7)
 pf() gb() ss(7) pf() gl() gb() gl()
 gb() gb() ss(7) pf() gb() ss(7) pf()
 gb() ss(7) pf() gr() gb() gr() gb()
 gb() ss(7) pf() gb() ss(7) pf() gb()
 ss(7) pf() gl() gb() gl() gb() gb()
 ss(7) pf() gb() ss(7) pf() gb() ss(7)
 pf() gb() gb() gb() gb() gb() gb()
 gb() gb() gr() gb() gr() gb() gb()
 ss(8) pf() gb() ss(8) pf() gb() ss(8)
 pf() gb() ss(8) pf() gb() ss(8) pf()
 gb() ss(8) pf() gb() ss(8) pf() gb()
 ss(8) pf() gb() gb() gb() gb() ss(8)
 pf() gb() ss(8) pf() gb() ss(8) pf()
 gb() ss(8) pf() gb() ss(8) pf() gb()
 ss(8) pf() gb() ss(8) pf() gb() ss(8)
 pf() gl() gb() gl() gb() ss(14) pf()
 gb() ss(8) pf() gb() ss(8) pf() gb()
 ss(8) pf() gb() ss(8) pf() gb() ss(8)
 pf() gb() ss(8) pf() gb() ss(8) pf()
 gb() ss(8) pf() gb() gb() gb() gb()
 ss(8) pf() gb() ss(8) pf() gb() ss(8)
 pf() gb() ss(8) pf() gb() ss(8) pf()
 gb() ss(8) pf() gb() ss(8) pf() gb()
 ss(8) pf() gb() ss(14) pf() gb()
 ss(15) pf() gr() gb() gr() gb() gb()
 gb() gb() ss(8) pf() gb() ss(8) pf()
 gb() ss(8) pf() gb() ss(8) pf() gb()
 ss(8) pf() gb() ss(8) pf() gb() ss(8)
 pf() gb() ss(8) pf() gb() gb() gb()
 gb() ss(8) pf() gb() ss(8) pf() gb()
 ss(8) pf() gb() ss(8) pf() gb() ss(8)
 pf() gb() ss(8) pf() gb() ss(8) pf()
 gb() ss(8) pf() gl() gb() gl() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() ss(7) pf() gb() ss(7) pf()
 gb() ss(7) pf() gr() gb() gr() gb()
 gb() ss(7) pf() gb() ss(7) pf() gb()
 ss(7) pf() gl() gb() gl() gb() gb()
 ss(7) pf() gb() ss(7) pf() gb() ss(7)
 pf() gr() gb() gr() gb() gb() ss(7)
 pf() gb() ss(7) pf() gb() ss(7) pf()
 gl() gb() gl() gb() gb() ss(7) pf()
 gb() ss(7) pf() gb() ss(7) pf() gr()
 gb() gr() gb() gb() ss(7) pf() gb()
 ss(7) pf() gb() ss(7) pf() gl() gb()
 gl() gb() gb() ss(7) pf() gb() ss(7)
 pf() gb() ss(7) pf() gr() gb() gr()
 gb() gb() ss(7) pf() gb() ss(7) pf()
 gb() ss(7) pf() gl() gb() gl() gb()
 gb() gb() gb() gr() gr() gb() gb()
 gb() ss(14) pf() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gr()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gl()
 gu() print("  working on layer 2 ...")
 gl() gl() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() ss(6)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() gr() gb() gr() gb() gb() ss(6)
 pf() gb() gb() gb() gb() ss(6) pf()
 gl() gb() gl() gb() gb() ss(6) pf()
 gb() ss(16) pf() gb() gb() gb() ss(6)
 pf() gr() gb() gr() gb() gb() ss(6)
 pf() gb() gb() gb() gb() ss(6) pf()
 gl() gb() gl() gb() gb() ss(6) pf()
 gb() gb() gb() gb() ss(6) pf() gr()
 gb() gr() gb() gb() ss(6) pf() gb()
 gb() gb() gb() ss(6) pf() gl() gb()
 gl() gb() gb() ss(6) pf() gb() gb()
 gb() ss(16) pf() gb() ss(6) pf() gr()
 gb() gr() gb() gb() ss(6) pf() gb()
 gb() gb() gb() ss(6) pf() gb() gb()
 gb() gb() gb() gb() gb() gl() gb()
 gl() gb() gb() ss(6) pf() gb() ss(6)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(6) pf() gb() ss(6) pf() gb()
 ss(6) pf() gb() ss(6) pf() gb() gb()
 gb() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(6) pf() gb() ss(6) pf() gb()
 ss(6) pf() gb() ss(6) pf() gb() ss(6)
 pf() gb() ss(6) pf() gb() gr() gb()
 gr() gb() gb() ss(6) pf() gb() gb()
 ss(16) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 ss(16) pf() gb() gb() gb() gb() gb()
 gl() gb() ss(6) pf() gl() gb() ss(6)
 pf() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 ss(8) pf() gb() ss(15) pf() gr() gb()
 gr() gb() gb() gb() ss(8) pf() gb()
 gb() gb() gb() gb() gb() ss(16) pf()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() ss(16) pf()
 gb() gl() gb() ss(6) pf() gl() gb()
 gb() ss(6) pf() gb() ss(6) pf() gb()
 ss(6) pf() gb() ss(6) pf() gb() ss(6)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(6) pf() gb() gb() gb() gb()
 ss(8) pf() gb() ss(8) pf() gb() ss(8)
 pf() gb() ss(8) pf() gb() ss(8) pf()
 gb() ss(8) pf() gb() ss(8) pf() gb()
 ss(8) pf() gr() gb() gr() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 ss(7) pf() gb() gb() gb() gb() ss(6)
 pf() gl() gb() gl() gb() gb() ss(7)
 pf() gb() ss(16) pf() gb() gb() gb()
 ss(7) pf() gr() gb() gr() gb() gb()
 ss(7) pf() gb() gb() gb() gb() ss(7)
 pf() gl() gb() gl() gb() gb() ss(7)
 pf() gb() gb() gb() gb() ss(7) pf()
 gr() gb() gr() gb() gb() ss(7) pf()
 gb() gb() gb() gb() ss(7) pf() gl()
 gb() gl() gb() gb() ss(7) pf() gb()
 gb() gb() ss(16) pf() gb() ss(7) pf()
 gr() gb() gr() gb() gb() ss(7) pf()
 gb() gb() gb() gb() ss(7) pf() gl()
 gb() gl() gb() gb() gb() gb() gb()
 gb() gr() gr() gb() gb() gb() ss(7)
 pf() gb() ss(7) pf() gb() ss(7) pf()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gr() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gl() gu()
 print("  working on layer 3 ...") gl()
 gl() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() ss(6) pf()
 gb() ss(6) pf() gb() ss(6) pf() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gr() gb() gr() gb() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(2) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(2)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() gb() gb() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gl()
 gb() gl() gb() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 gb() gb() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(3) pf() gb() ss(3) pf() gr() gb()
 gr() gb() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() gb()
 gb() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(2) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(4) pf() gl() gb() gl()
 gb() gb() ss(2) pf() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() gb() gb()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gr() gb() gr() gb()
 gb() ss(3) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(3) pf() gb() gb() gb() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(2) pf() gl() gb() gl() gb() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(2) pf() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() gb() gb() gb() ss(3)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(3)
 pf() gr() gb() gr() gb() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() gb() gb() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gl() gb() gl() gb() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() gb() gb() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 gr() gb() gr() gb() gb() ss(6) pf()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gl() gb()
 ss(6) pf() gl() gb() ss(6) pf() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() ss(6) pf()
 gb() ss(15) pf() gr() gb() gr() gb()
 gb() gb() ss(6) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gl() gb() ss(6) pf() gl()
 gb() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() gb() gb()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(5) pf() gb() ss(5) pf() gb() ss(5)
 pf() gb() ss(5) pf() gb() ss(5) pf()
 gb() ss(5) pf() gr() gb() gr() gb()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(5) pf() gb() ss(5) pf() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(5) pf()
 gb() ss(5) pf() gb() gb() gb() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(4) pf() gl() gb() gl() gb() gb()
 ss(4) pf() gb() ss(5) pf() gb() ss(5)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(4) pf() gb() gb() gb() gb() ss(5)
 pf() gb() ss(5) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(5) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(3)
 pf() gr() gb() gr() gb() gb() ss(5)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(5) pf() gb()
 ss(5) pf() gb() ss(5) pf() gb() ss(5)
 pf() gb() gb() gb() gb() ss(4) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(5)
 pf() gb() ss(5) pf() gb() ss(4) pf()
 gl() gb() gl() gb() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(5) pf() gb() ss(5) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() gb() gb() gb() ss(5) pf() gb()
 ss(5) pf() gb() ss(5) pf() gb() ss(5)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(5) pf() gr()
 gb() gr() gb() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(5)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 gb() gb() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(5) pf() gb() ss(5) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(4) pf() gb() ss(4) pf() gl() gb()
 gl() gb() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(5) pf() gb() ss(5) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() gb()
 gb() gb() ss(5) pf() gb() ss(5) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(5) pf() gb() ss(5) pf() gb() ss(5)
 pf() gb() ss(5) pf() gr() gb() gr()
 gb() gb() ss(5) pf() gb() ss(5) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(5) pf() gb() ss(5) pf() gb() ss(5)
 pf() gb() ss(5) pf() gb() gb() gb()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(5) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(5) pf() gb() ss(4) pf()
 gb() ss(4) pf() gl() gb() gl() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() ss(6) pf() gb() ss(6)
 pf() gb() ss(6) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gr()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gl()
 gu() print("  working on layer 4 ...")
 gl() gl() gb() gb() gb() ss(1) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(1) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(1) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() gr()
 gb() gr() gb() gb() ss(1) pf() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gl() gb() ss(1)
 pf() gl() gb() ss(1) pf() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() ss(1) pf() gr()
 gb() gr() gb() gb() ss(1) pf() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gl() gb() ss(1)
 pf() gl() gb() ss(1) pf() gb() gb()
 gb() gb() ss(16) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() ss(16) pf() gb() gb() gb()
 gb() ss(1) pf() gr() gb() gr() gb()
 gb() ss(1) pf() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gl() gb() ss(1) pf() gl() gb()
 ss(1) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() ss(1) pf() gr() gb() gr() gb()
 gb() ss(1) pf() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gl() gb() ss(1) pf() gl() gb()
 ss(1) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() ss(1) pf() gr() gb() gr() gb()
 gb() ss(1) pf() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gl() gb() ss(1) pf() gl() gb()
 ss(1) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() ss(1) pf() gb() ss(15) pf() gr()
 gb() gr() gb() gb() gb() ss(1) pf()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gl() gb()
 ss(1) pf() gl() gb() ss(1) pf() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() ss(1) pf()
 gr() gb() gr() gb() gb() ss(1) pf()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gl() gb()
 ss(1) pf() gl() gb() ss(1) pf() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() ss(1) pf()
 gr() gb() gr() gb() gb() ss(1) pf()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gl() gb()
 ss(1) pf() gl() gb() ss(1) pf() gb()
 gb() gb() gb() ss(16) pf() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() ss(16) pf() gb() gb()
 gb() gb() ss(1) pf() gr() gb() gr()
 gb() gb() ss(1) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() ss(1) pf() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() ss(1) pf() gr() gb() gr()
 gb() gb() ss(1) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gl() gb() ss(1) pf() gl()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gr() gr() gb() gb() gb() ss(8) pf()
 gb() ss(8) pf() gb() ss(8) pf() gb()
 ss(8) pf() gb() ss(8) pf() gb() ss(8)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(6) pf() gb() ss(6) pf() gb()
 ss(6) pf() gb() ss(6) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(1) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() gr()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gl()
 gd() gd() gd()
 print("  Done: lower half spawn area")
 
-- go down & restock & go up ---------
gl() for i=1,8 do gb() end 
gr() for i=1,8 do gf() end 
for i=1,23 do gd() end
gl() gl() ss(1)
for i=1,6 do sf() end
--ss(9) Df()
if noLadder==0 then ss(14) Df() ss(15) Df() end
gr() gr()
for i=1,23 do gu() end
for i=1,8 do gb() end gr()
for i=1,8 do gb() end gl()
gu() gu() gu() gu()

 print("Next part: upper half spawn area")
  print("  working on layer 1 ...") gl()
 gl() gb() gb() gb() ss(6) pf() gb()
 ss(6) pf() gb() ss(6) pf() gb() ss(6)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(6) pf() gb() ss(6) pf() gb()
 ss(6) pf() gb() ss(6) pf() gb() ss(6)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(6) pf() gb() ss(6) pf() gb()
 ss(6) pf() gb() ss(6) pf() gb() ss(6)
 pf() gb() ss(6) pf() gb() gr() gb()
 gr() gb() gb() ss(5) pf() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gl() gb() ss(6) pf()
 gl() gb() ss(6) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() ss(5) pf() gr() gb()
 gr() gb() gb() ss(5) pf() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gl() gb() ss(6) pf()
 gl() gb() ss(6) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() ss(5) pf() gr() gb()
 gr() gb() gb() ss(5) pf() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gl() gb() ss(6) pf()
 gl() gb() ss(6) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() ss(5) pf() gr() gb()
 gr() gb() gb() ss(5) pf() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gl() gb() ss(6) pf()
 gl() gb() ss(6) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() ss(5) pf() gr() gb()
 gr() gb() gb() ss(5) pf() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gl() gb() ss(6) pf()
 gl() gb() ss(6) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() ss(5) pf() gb() ss(15)
 pf() gr() gb() gr() gb() gb() gb()
 ss(5) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gl() gb() ss(6) pf() gl() gb() ss(6)
 pf() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 ss(5) pf() gr() gb() gr() gb() gb()
 ss(5) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gl() gb() ss(6) pf() gl() gb() ss(6)
 pf() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 ss(5) pf() gr() gb() gr() gb() gb()
 ss(5) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gl() gb() ss(6) pf() gl() gb() ss(6)
 pf() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 ss(5) pf() gr() gb() gr() gb() gb()
 ss(5) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gl() gb() ss(6) pf() gl() gb() ss(6)
 pf() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 ss(5) pf() gr() gb() gr() gb() gb()
 ss(5) pf() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gl() gb() ss(6) pf() gl() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gr() gr()
 gb() gb() gb() ss(5) pf() gb() ss(5)
 pf() gb() ss(5) pf() gb() ss(5) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(5) pf() gb() ss(5) pf() gb() ss(5)
 pf() gb() ss(5) pf() gb() ss(5) pf()
 gb() ss(5) pf() gb() ss(5) pf() gb()
 ss(5) pf() gb() ss(5) pf() gb() ss(5)
 pf() gb() ss(5) pf() gb() ss(5) pf()
 gb() ss(5) pf() gb() gr() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gl() gu()
 print("  working on layer 2 ...") gl()
 gl() gb() gr() gb() gl() gb() gb()
 ss(1) pf() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(1) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gr() gb() gr() gb() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(1) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gl() gb()
 gl() gb() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(2) pf() gr() gb() gr() gb()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(11)
 pf() gb() ss(11) pf() gb() ss(11) pf()
 gb() ss(11) pf() gb() ss(2) pf() gb()
 ss(1) pf() gb() ss(6) pf() gb() ss(6)
 pf() gb() ss(1) pf() gb() ss(6) pf()
 gb() ss(6) pf() gb() ss(6) pf() gb()
 ss(6) pf() gb() ss(1) pf() gb() ss(1)
 pf() gl() gb() gl() gb() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(1) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(1) pf() gb() ss(6)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(2) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gr() gb() gr() gb() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(1) pf() gb() ss(10) pf()
 gb() ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(1) pf() gb() ss(1)
 pf() gl() gb() gl() gb() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(10) pf()
 gb() ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(1) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(11) pf()
 gb() ss(11) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gr() gb() gr() gb() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(1) pf()
 gl() gb() gl() gb() gb() ss(1) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(3) pf() gb() ss(2)
 pf() gb() ss(2) pf() gb() ss(2) pf()
 gb() ss(2) pf() gb() ss(2) pf() gb()
 ss(2) pf() gb() ss(2) pf() gb() ss(2)
 pf() gb() gb() ss(14) pf() gr() gb()
 gr() gb() ss(14) pf() gb() gb() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(10)
 pf() gb() ss(10) pf() gb() ss(10) pf()
 gb() ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(1) pf() gb() ss(1)
 pf() gb() ss(1) pf() gb() ss(1) pf()
 gl() gb() gl() gb() gb() ss(1) pf()
 gb() ss(1) pf() gb() ss(1) pf() gb()
 ss(1) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() gb() ss(14) pf() gr() gb()
 gr() gb() gb() gb() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(1) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gl() gb() gl() gb() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(3) pf() gb() ss(11) pf()
 gb() ss(11) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gr() gb() gr() gb() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(3) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(10) pf()
 gb() ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(10) pf() gb()
 ss(10) pf() gb() ss(4) pf() gb() ss(4)
 pf() gl() gb() gl() gb() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(3) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gr() gb() gr() gb() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(11) pf() gb()
 ss(11) pf() gb() ss(3) pf() gb() ss(6)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(6) pf() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gl() gb() gl() gb() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(6) pf() gb() ss(6) pf() gb() ss(4)
 pf() gb() ss(6) pf() gb() ss(6) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gr() gb()
 gr() gb() gb() ss(3) pf() gb() ss(3)
 pf() gb() ss(3) pf() gb() ss(3) pf()
 gb() ss(3) pf() gb() ss(3) pf() gb()
 ss(3) pf() gb() ss(3) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(4) pf() gl() gb() gl() gb()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() ss(4) pf() gb() ss(4) pf()
 gb() ss(4) pf() gb() ss(4) pf() gb()
 ss(4) pf() gb() ss(4) pf() gb() ss(4)
 pf() gb() gb() gr() gb() gr() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gr() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gl() gu()
 print("  working on layer 3 ...") gl()
 gl() gb() gr() gb() gl() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() ss(16) pf() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gr() gb() gb() gr() gb() gb()
 gb() gb() gb() gb() ss(16) pf() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() ss(16)
 pf() gb() gb() gl() gb() gb() gb()
 gb() gb() gb() gb() gl() gb() gb()
 ss(16) pf() gb() gb() gb() gb() gb()
 gb() ss(16) pf() gb() gb() gb() gb()
 gb() gb() ss(16) pf() gb() gb() gb()
 gb() gb() gb() ss(16) pf() gb() gb()
 gr() gb() gb() gb() gb() gb() gb()
 gb() gr() gb() gb() gb() gb() gb()
 gb() ss(16) pf() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() ss(16) pf() gb() gb()
 gl() gb() gb() gl() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() ss(16) pf() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gr() gb() gr() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gr() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gb() gb()
 gb() gb() gb() gb() gb() gl() gd()
 gd()
 print("   Done: upper half spawn area")


 -- go down last time
gd() gd() gd() gd() 
gl() for i=1,8 do gb() end 
gr() for i=1,8 do gf() end 
for i=1,23 do gd() end

print("Let's have some finishing touch...")
-- water
gr() gf() gf() gl()
gf() gf() gf()
for i=1,24 do gu() end
for i=1,4 do water() gr() end gr()
-- remove torches
gu() gu()
gf() gf() gf() gf() gf() gf() gl()
gf() gf() gf() gf() gf() 
getTorches() getTorches() getTorches()
ss(12) pf() os.sleep(0.3) pf()
for i=1,5 do gb() end gr()
for i=1,6 do gb() end gl() gl()
-- return
for i=1,26 do gd() end
gb() gb() gb()
gl() gf() gf()
-- drop remaining
gl()
for i=1,16 do ss(i) Df() end
gr() gr()
print("Done. Looks nice to me ;)")
 os.sleep(0.4)
 print("***************************************")
 print("* Check out YouTube for more videos   *")
 print("* and turtle programs by Kaikaku :)   *")
 print("***************************************")